language: ruby
rvm:
- 2.6.4
env:
  matrix:
  - DB=postgresql
before_script:
- cp config/database.travis.yml config/database.yml
- psql -c 'create database travis_ci_test;' -U postgres
- RAILS_ENV=test bundle exec rake db:create db:migrate --trace
- wget http://chromedriver.storage.googleapis.com/2.27/chromedriver_linux64.zip
- unzip chromedriver_linux64.zip
- sudo apt-get install libnss3
- sudo apt-get --only-upgrade install google-chrome-stable
- sudo cp chromedriver /usr/local/bin/.
- sudo chmod +x /usr/local/bin/chromedriver
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
cache:
  bundler: true
  directories:
  - node_modules
  yarn: true
services:
- postgresql
install:
- bundle install
- nvm install node
- node -v
- npm i -g yarn
- yarn
script:
- bundle exec rails webpacker:compile
- bundle exec rails spec
deploy:
  provider: heroku
  api_key:
    secure: QtUMruCutmPlTSj9EzTrtFr2P41+70NlXRQR7+P+JzY2SLflgmXewsssyLa9ABkmzdUSQOfxg56q6PPT2tuiFGEGgQS0jNm2qq2YoNjjuFvDKmzGsvYv2IM2fctgFeeRVE3wcyCVtREx6o4tgmBzqppTmpfPiiprecaRUkqbp+TY3WTiLAlH0vZ1Vpt4H/pLAqLI2b5EtqTl7AOd+T3KW78ge/nb5zYqMu94iQE3aDtzFcpeV1XnoONCmIU39GRSEvDNJtptwo3crPU8IqCVCfjWpOaObNQbXzEqkpIS8kPi3uB2kcHLYskMsaIOBJ6eK4FW48yC80L9/Ua2GzmKlxaU+SaQdWh14VPftuoDI9L0sJAzRdCb60+JLM88o+Vp3MiZn7KgAHpxNpADq7fQwtUkOSqG2eq20jq69t/9dBBvl0A5hp51l5ScLZk3yDPbfm+CsZTMtoVr7/M2TD0cpyQNdt8XEtaqnJfEuiFyBbM0wLkBay8UN9OB8FQZSFwoYG6hff2ugT20ZAZzQsyrEQj026tfGqbKOfA1i3sVf1xBbD0FjaBy9hO9Ce5EqIMNGfye6liNIiHF325CUC09Hddd84ellODo1Vi4OEcq0JsjFQZAPVf3GIPD37pgB0DXuHK8BdncOjcRIgCJN2JSz0gIR6TtX05qXddQ+FDq0ME=
  app: oh-hey
  run: rake db:migrate
