language: ruby
rvm:
- 2.6.4
env:
  matrix:
  - DB=postgresql
addons:
  chrome: stable
  apt:
    packages:
    - chromium-chromedriver
before_script:
- cp config/database.travis.yml config/database.yml
- psql -c 'create database travis_ci_test;' -U postgres
- RAILS_ENV=test bundle exec rake db:create db:migrate --trace
before_install:
- wget https://github.com/mozilla/geckodriver/releases/download/v0.11.1/geckodriver-v0.11.1-linux64.tar.gz
- mkdir geckodriver
- tar -xzf geckodriver-v0.11.1-linux64.tar.gz -C geckodriver
- export PATH=$PATH:$PWD/geckodriver
cache:
  bundler: true
  directories:
  - node_modules
  yarn: true
services:
- postgresql
install:
- bundle install
- nvm install node
- node -v
- npm i -g yarn
- yarn
script:
- bundle exec rails webpacker:compile
- bundle exec rails spec
deploy:
  provider: heroku
  api_key:
    secure: bHJfw07ZbYkrtbies0STEJM8ceT54C6DNK2Bbu9/r7b3V94z0zGM1eCJKmkXWCjAnNAxzflqmm6wFHt8t38HD1PY5nkj+7o+z2I119/nB8ZGgRhNQbJVrV5CnynUA56eyDyKpiKGeekkCqNCi7qVJuiqe2kvMygPyJ4/efZAK3XAsigVRR01iRsrRU0DNW/kFVuRi49RbETXB+rjoUmSqV7OsLy3mToqhveO7iu5aBIHEBGHVKGXFgotzAvXqoMmM/6xq/Vsxt0wBRUJ+kjRj6VlV2w+9pXm+8w7fMgoOb9vtGAsv1tgdfuh12eX85mlrsPvqP/qsTEuEN5mbDcwSKqhqBzZ5kRw40nXGAlsorN54hYbuyLSBkAxHRlQW7Tm+rm1sGCgolKN2CTFWBvChsvr4BkCzrmhVvBxmfOR/qAPYEJEOsr69AoOEVqUSO7u51Eqe+tRtdkLlUJn3dOanXea+FxHkMckE9bTPb+I007V0KFMeeEXVHE1YE5UOOrPgkLMQ9TxGVQryG7rD3zLhv23vIGnbojJFoUmgWkUYoJnNma2qZ9QMzQSIiVxlEeQWxrpkdCuU32a81ZHwhXMlSpCB+odExg+ZyshkxEWs/RFgAa7GuQWnEujElsjtuFXqNblkjONs6Z3t2crEOLb6x9glzp8wNwAfhI5lBymVvI=
  app: oh-hey
  on:
    repo: notmarkmiranda/dozen
