language: ruby
rvm:
- 2.6.4
env:
  matrix:
  - DB=postgresql
before_script:
- cp config/database.travis.yml config/database.yml
- psql -c 'create database travis_ci_test;' -U postgres
- RAILS_ENV=test bundle exec rake db:create db:migrate --trace
cache:
  bundler: true
  directories:
  - node_modules
  yarn: true
services:
- postgresql
install:
- bundle install
- nvm install node
- node -v
- npm i -g yarn
- yarn
script:
- bundle exec rails webpacker:compile
- bundle exec rails spec
deploy:
  provider: heroku
  api_key:
    secure: 0WcF4Ryt4UN2Q4qkEGumUTBFRBZ+tNttiyYEW8b7cRHJnPbqrL/TBe+oixowFsyH8DuCUCSsOEI6YZR1sr5vBwWxme+EdJC3FM5MKUvOMSiUBvVBk6bO4nLoh6mMJkgQ1AZRJ4mOrXZZ5LegfIPZBCewF1kZsmUB87iPjCopBOjdNZpNIhRIHqqVP1ATB29yAlj+Rd4JwW+IeHcio6ji/UHWotobosTJ71Skd881ky+86qaSvgEzNskuUEi6pAbgWI5b1+LcJSiDwzz1Zxa7+CGSZ8Ji2CDEZU5xVwrTgu8DtCtG1gHaWkts5R/UT7AC6/sx385dLQUWD8HMwdwLmmWH3pIQNMxX+EV9U3vzbydg9hbbrNUiAWGF1N+SLyMzPk6JiQs78g3S6UgeMsf7IvaFLs6SGnaM7uB/aB3+YoVyiHH+PujUqwq2h0iLM2fuIQ2vQm0Dru0r4DuYJSSO7A7DFFrMvA2zFqnAvzukOd9CSx/QZSsLoIsswhGy86PNCbn8IS7i/2flBkANByho4egdqvECf0SRHLSigma68/v4eH4TIRuA9h1+MNurhvQIMAc5IdjQvQ01ofMuKIA6LXJCRK4n+0zS5kJlY8LTqt8WD0tzsT/pwOfWl/YD/BcIjy2Pfjbl/Ph6LMzOt0Letp0MkiIaOrhBEO8mvDaWUHI=
  app: oh-hey
  run: "rake db:migrate"
